global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

alerting: # TBD
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s

scrape_configs:

- job_name: prometheus # scrape metrics from the prometheus host
  honor_timestamps: true
  static_configs:
   - targets: ['localhost:9090']

- job_name: grafana # scrape metrics from the grafana host
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
   - targets: ['grafana:3000']

- job_name: docker # scrape metrics from the docker engine host
  static_configs:
      - targets: ["host.docker.internal:9323"]

- job_name: docker-cAdvisor # scrape metrics from the cAdvisor(docker based monitoring agent) host
  static_configs:
      - targets: ["host.docker.internal:8080"]

- job_name: pushgateway # scrape metrics from the pushgateway (for any custom/short-lived metrics) host
  static_configs:
      - targets: ["host.docker.internal:9091"] # Sending metrics to push gateway using the send_metrics.py


# Send the metrics to Grafana cloud - https://makram039.grafana.net/connections/add-new-connection/hmInstancePromId?remoteWrite=direct&from=onboarding
#remote_write:
#  - url: <Remote URL>
#    basic_auth:
#      username: <Grafana cloud username>
#      password: <Grafana Token>